name: DataOps-Automation
on: [push]

jobs:
  quality-and-deploy:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3

      - name: Set up Python
        uses: actions/setup-python@v4
        with:
          python-version: '3.9'

      - name: Install Dependencies
        run: pip install pandas

      - name: Run Quality Gate
        run: python validate.py

      - name: Terraform Deploy
        if: success() # ONLY runs if the Python test above passes!
        run: |
          terraform init
          terraform apply -auto-approve